---
- name: Проверить наличие kubectl
  command: kubectl version --client
  register: kubectl_check
  changed_when: false

- name: Показать версию kubectl
  debug:
    msg: "{{ kubectl_check.stdout }}"

- name: Проверить наличие docker
  command: docker --version
  register: docker_check
  changed_when: false

- name: Показать версию docker
  debug:
    msg: "{{ docker_check.stdout }}"

- name: Проверить соединение с кластером
  command: kubectl cluster-info
  register: cluster_info
  changed_when: false

- name: Показать информацию о кластере
  debug:
    var: cluster_info.stdout_lines

- name: Установить pip зависимости для kubernetes
  pip:
    name: kubernetes
    extra_args: --user --break-system-packages
    state: present

- name: Скачать образ nginx локально
  command: docker pull nginx:latest
  register: docker_pull
  changed_when: "'Downloaded' in docker_pull.stdout"

- name: Загрузить образ nginx в minikube
  command: minikube image load nginx:latest
  changed_when: false
