---
- name: Проверить что minikube установлен
  command: minikube version
  register: minikube_version
  changed_when: false

- name: Показать версию minikube
  debug:
    msg: "{{ minikube_version.stdout }}"

- name: Проверить статус minikube
  command: minikube status
  register: minikube_status
  changed_when: false
  ignore_errors: true

- name: Запустить minikube с flannel CNI и 3 нодами
  command: >
    minikube start
    --driver={{ minikube_driver }}
    --cpus={{ minikube_cpus }}
    --memory={{ minikube_memory }}
    --cni={{ minikube_cni }}
    --nodes={{ minikube_nodes }}
  when: "'Running' not in minikube_status.stdout"
  register: minikube_start

- name: Подождать пока все ноды будут Ready
  command: kubectl wait --for=condition=Ready nodes --all --timeout=180s
  when: minikube_start is changed
  changed_when: false

- name: Показать финальный статус кластера
  command: minikube status
  register: final_status
  changed_when: false

- name: Вывести статус
  debug:
    var: final_status.stdout_lines
